name: build nixos-runner
on:
  - push
jobs:
  build:
    runs-on: nixos
    steps:
      - uses: actions/checkout@v4
      - run: set
      - name: Set up cache
        run: |
          nix run .#attic-client -- login ${{ vars.ATTIC_SERVER }} ${{ vars.ATTIC_ENDPOINT }} ${{ secrets.ATTIC_TOKEN }}
          nix run .#attic-client -- use ${{ vars.ATTIC_CACHE }}
      - name: Build
        run: nix build -L .#nixos-runner
      - name: Push results to cache
        run: |
          nix run .#attic-client -- push ${{ vars.ATTIC_CACHE }} result
      - name: Push container
        run: nix run .#push-container -- result
        env:
          REGISTRY: ${{ vars.FORGEJO_REGISTRY }}
          REPOSITORY: ${{ vars.FORGEJO_USERNAME }}/nixos-runner
          USERNAME: ${{ vars.FORGEJO_USERNAME }}
          PASSWORD: ${{ secrets.FORGEJO_PASSWORD }}
      - name: Push container
        run: nix run .#push-container -- result
        env:
          REGISTRY: ${{ vars.DOCKER_REGISTRY }}
          REPOSITORY: ${{ vars.DOCKER_USERNAME }}/nixos-runner
          USERNAME: ${{ vars.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
