name: build nixos-runner
on:
  - push
jobs:
  build:
    runs-on: nixos
    steps:
      - name: Checkout code
        uses: https://code.forgejo.org/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up cache
        run: |
          attic login ${{ vars.ATTIC_SERVER }} ${{ vars.ATTIC_ENDPOINT }} ${{ secrets.ATTIC_TOKEN }}
          attic use ${{ vars.ATTIC_CACHE }}
          nix path-info --all | LANG=C sort > before

      - name: Build
        run: nix build -L .#nixos-runner

      - name: Push container to local registry
        run: nix run .#push-container -- result
        env:
          REGISTRY: ${{ vars.FORGEJO_REGISTRY }}
          REPOSITORY: ${{ vars.FORGEJO_USERNAME }}/nixos-runner
          USERNAME: ${{ vars.FORGEJO_USERNAME }}
          PASSWORD: ${{ secrets.FORGEJO_PASSWORD }}

      - name: Push container to docker registry
        run: nix run .#push-container -- result
        env:
          REGISTRY: ${{ vars.DOCKER_REGISTRY }}
          REPOSITORY: ${{ vars.DOCKER_USERNAME }}/nixos-runner
          USERNAME: ${{ vars.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push results to cache
        run: |
          nix path-info --all | LANG=C sort > after
          comm -13 before after > new
          cat new | attic push ${{ vars.ATTIC_CACHE }} --stdin
