name: build nixos-runner
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/jcollie/nixos-runner:latest
    steps:
      - uses: actions/checkout@v4
      - run: set
      - run: nix build -L .#nixos-runner
      - run: nix run .#push-container -- result
        env:
          REGISTRY: https://git.ocjtech.us/${{ github.repository_owner }}
          REPOSITORY: nixos-runner
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ github.token }}
