name: build nixos-runner
on:
  - push
jobs:
  build:
    runs-on: nixos
    steps:
      - uses: actions/checkout@v4
      - run: set
      - run: nix build -L .#nixos-runner
      - run: nix run .#push-container -- result
        env:
          REGISTRY: git.ocjtech.us
          REPOSITORY: ${{ github.repository_owner }}/nixos-runner
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ github.token }}
