name: build nixos-runner
on:
  - push
jobs:
  build:
    runs-on: nixos
    steps:
      - uses: actions/checkout@v4
      - run: set
      - name: Set up cache
        run: |
          nix run .#attic-client -- login cloud03 ${{ vars.ATTIC_ENDPOINT }} ${{ secrets.ATTIC_TOKEN }}
          nix run .#attic-client -- use ocjtech-1
      - name: Build
        run: nix build -L .#nixos-runner
      - name: Push results to cache
        run: |
          nix run .#attic-client -- push ocjtech-1 result
      - name: Push container
        run: nix run .#push-container -- result
        env:
          REGISTRY: ${{ vars.FORGEJO_REGISTRY }}
          REPOSITORY: ${{ vars.FORGEJO_USERNAME }}/nixos-runner
          USERNAME: ${{ vars.FORGEJO_USERNAME }}
          PASSWORD: ${{ secret.FORGEJO_PASSWORD }}
