name: build nixos-runner
on:
  - push
jobs:
  build:
    runs-on: nixos
    steps:
      - uses: actions/checkout@v4
      - run: set
      - name: Set up cache
        run: |
          nix run .#attic-client -- login cloud03 ${{ vars.ATTIC_ENDPOINT }} ${{ secrets.ATTIC_TOKEN }}
          nix run .#attic-client -- use ocjtech-1
      - name: Build
        run: nix build -L .#nixos-runner
      - run: |
          nix run .#attic-client -- push ocjtech-1 result
      - name: Push results to cache
        run: nix run .#push-container -- result
        env:
          REGISTRY: git.ocjtech.us
          REPOSITORY: ${{ github.repository_owner }}/nixos-runner
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ github.token }}
